pr to add main.c
liwenqiu/foo pull request #4
Opened 2024-01-16 11:49 UTC by lucia-lau

this is a pr test

2024-01-16 11:56 UTC, liwenqiu requested changes
this is the first review

2024-01-16 11:56 UTC, liwenqiu commented on main.c
> +int main() {
1st review comment

2024-01-16 11:58 UTC, lucia-lau commented on main.c
> +int main() {
got it

2024-01-16 12:03 UTC, liwenqiu commented on main.c
> +int main() {
1-1

2024-01-16 12:05 UTC, liwenqiu commented on main.c
> +  return 0;
may we print a 'hello world' string

2024-01-16 12:07 UTC, lucia-lau commented on main.c
> +int main() {
1-2

2024-01-16 12:19 UTC, liwenqiu commented on main.c
> +int main() {
1-3

2024-01-16 12:19 UTC, liwenqiu commented on main.c
> +int main() {
1-4

2024-01-16 12:19 UTC, liwenqiu commented on main.c
> +int main() {
1-5

2024-01-16 12:19 UTC, liwenqiu commented on main.c
> +int main() {
1-6

2024-01-16 12:19 UTC, liwenqiu commented on main.c
> +int main() {
1-7

2024-01-16 12:19 UTC, liwenqiu commented on main.c
> +int main() {
1-8

2024-01-16 12:19 UTC, liwenqiu commented on main.c
> +int main() {
1-9

2024-01-16 12:19 UTC, liwenqiu commented on main.c
> +int main() {
1-10

2024-01-16 12:20 UTC, liwenqiu commented on main.c
> +int main() {
1-11

2024-01-16 12:20 UTC, liwenqiu commented on main.c
> +int main() {
1-12

2024-01-16 12:20 UTC, liwenqiu commented on main.c
> +int main() {
1-13

2024-01-16 12:35 UTC, liwenqiu commented on main.c
> +int main() {
> 1-13

1-14

2024-01-16 12:38 UTC, liwenqiu commented on main.c
> +
test range comment

2025-05-23 04:37 UTC, liwenqiu approved these changes

2025-05-23 04:37 UTC, liwenqiu commented on main.c
> +#include <stdio.h>
new review comment

2025-09-19 03:31 UTC, merged